/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BalesRouteImport } from './routes/bales'
import { Route as ClothesRouteImport } from './routes/clothes'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MoreRouteImport } from './routes/more'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as BalesIndexRouteImport } from './routes/bales/index'
import { Route as BalesIdRouteImport } from './routes/bales/$id'
import { Route as BalesNewRouteImport } from './routes/bales/new'
import { Route as ClothesIndexRouteImport } from './routes/clothes/index'
import { Route as ClothesIdRouteImport } from './routes/clothes/$id'
import { Route as ClothesNewRouteImport } from './routes/clothes/new'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as CustomersIdRouteImport } from './routes/customers/$id'
import { Route as PhotosIdRouteImport } from './routes/photos/$id'
import { Route as SalesNewRouteImport } from './routes/sales/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BalesRoute = BalesRouteImport.update({
  id: '/bales',
  path: '/bales',
  getParentRoute: () => rootRouteImport,
} as any)
const ClothesRoute = ClothesRouteImport.update({
  id: '/clothes',
  path: '/clothes',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const BalesIndexRoute = BalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BalesRoute,
} as any)
const BalesIdRoute = BalesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BalesRoute,
} as any)
const BalesNewRoute = BalesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BalesRoute,
} as any)
const ClothesIndexRoute = ClothesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClothesRoute,
} as any)
const ClothesIdRoute = ClothesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClothesRoute,
} as any)
const ClothesNewRoute = ClothesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ClothesRoute,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomersRoute,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomersRoute,
} as any)
const PhotosIdRoute = PhotosIdRouteImport.update({
  id: '/photos/$id',
  path: '/photos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesNewRoute = SalesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SalesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bales': typeof BalesRouteWithChildren
  '/clothes': typeof ClothesRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/expenses': typeof ExpensesRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRouteWithChildren
  '/bales/$id': typeof BalesIdRoute
  '/bales/new': typeof BalesNewRoute
  '/clothes/$id': typeof ClothesIdRoute
  '/clothes/new': typeof ClothesNewRoute
  '/customers/$id': typeof CustomersIdRoute
  '/photos/$id': typeof PhotosIdRoute
  '/sales/new': typeof SalesNewRoute
  '/bales/': typeof BalesIndexRoute
  '/clothes/': typeof ClothesIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/expenses': typeof ExpensesRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRouteWithChildren
  '/bales/$id': typeof BalesIdRoute
  '/bales/new': typeof BalesNewRoute
  '/clothes/$id': typeof ClothesIdRoute
  '/clothes/new': typeof ClothesNewRoute
  '/customers/$id': typeof CustomersIdRoute
  '/photos/$id': typeof PhotosIdRoute
  '/sales/new': typeof SalesNewRoute
  '/bales': typeof BalesIndexRoute
  '/clothes': typeof ClothesIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bales': typeof BalesRouteWithChildren
  '/clothes': typeof ClothesRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/expenses': typeof ExpensesRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRouteWithChildren
  '/bales/$id': typeof BalesIdRoute
  '/bales/new': typeof BalesNewRoute
  '/clothes/$id': typeof ClothesIdRoute
  '/clothes/new': typeof ClothesNewRoute
  '/customers/$id': typeof CustomersIdRoute
  '/photos/$id': typeof PhotosIdRoute
  '/sales/new': typeof SalesNewRoute
  '/bales/': typeof BalesIndexRoute
  '/clothes/': typeof ClothesIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bales'
    | '/clothes'
    | '/customers'
    | '/expenses'
    | '/login'
    | '/more'
    | '/reports'
    | '/sales'
    | '/bales/$id'
    | '/bales/new'
    | '/clothes/$id'
    | '/clothes/new'
    | '/customers/$id'
    | '/photos/$id'
    | '/sales/new'
    | '/bales/'
    | '/clothes/'
    | '/customers/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/expenses'
    | '/login'
    | '/more'
    | '/reports'
    | '/sales'
    | '/bales/$id'
    | '/bales/new'
    | '/clothes/$id'
    | '/clothes/new'
    | '/customers/$id'
    | '/photos/$id'
    | '/sales/new'
    | '/bales'
    | '/clothes'
    | '/customers'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/bales'
    | '/clothes'
    | '/customers'
    | '/expenses'
    | '/login'
    | '/more'
    | '/reports'
    | '/sales'
    | '/bales/$id'
    | '/bales/new'
    | '/clothes/$id'
    | '/clothes/new'
    | '/customers/$id'
    | '/photos/$id'
    | '/sales/new'
    | '/bales/'
    | '/clothes/'
    | '/customers/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BalesRoute: typeof BalesRouteWithChildren
  ClothesRoute: typeof ClothesRouteWithChildren
  CustomersRoute: typeof CustomersRouteWithChildren
  ExpensesRoute: typeof ExpensesRoute
  LoginRoute: typeof LoginRoute
  MoreRoute: typeof MoreRoute
  ReportsRoute: typeof ReportsRoute
  SalesRoute: typeof SalesRouteWithChildren
  PhotosIdRoute: typeof PhotosIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bales': {
      id: '/bales'
      path: '/bales'
      fullPath: '/bales'
      preLoaderRoute: typeof BalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clothes': {
      id: '/clothes'
      path: '/clothes'
      fullPath: '/clothes'
      preLoaderRoute: typeof ClothesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bales/': {
      id: '/bales/'
      path: '/'
      fullPath: '/bales/'
      preLoaderRoute: typeof BalesIndexRouteImport
      parentRoute: typeof BalesRoute
    }
    '/bales/$id': {
      id: '/bales/$id'
      path: '/$id'
      fullPath: '/bales/$id'
      preLoaderRoute: typeof BalesIdRouteImport
      parentRoute: typeof BalesRoute
    }
    '/bales/new': {
      id: '/bales/new'
      path: '/new'
      fullPath: '/bales/new'
      preLoaderRoute: typeof BalesNewRouteImport
      parentRoute: typeof BalesRoute
    }
    '/clothes/': {
      id: '/clothes/'
      path: '/'
      fullPath: '/clothes/'
      preLoaderRoute: typeof ClothesIndexRouteImport
      parentRoute: typeof ClothesRoute
    }
    '/clothes/$id': {
      id: '/clothes/$id'
      path: '/$id'
      fullPath: '/clothes/$id'
      preLoaderRoute: typeof ClothesIdRouteImport
      parentRoute: typeof ClothesRoute
    }
    '/clothes/new': {
      id: '/clothes/new'
      path: '/new'
      fullPath: '/clothes/new'
      preLoaderRoute: typeof ClothesNewRouteImport
      parentRoute: typeof ClothesRoute
    }
    '/customers/': {
      id: '/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/photos/$id': {
      id: '/photos/$id'
      path: '/photos/$id'
      fullPath: '/photos/$id'
      preLoaderRoute: typeof PhotosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/new': {
      id: '/sales/new'
      path: '/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof SalesNewRouteImport
      parentRoute: typeof SalesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BalesRouteChildren {
  BalesIdRoute: typeof BalesIdRoute
  BalesNewRoute: typeof BalesNewRoute
  BalesIndexRoute: typeof BalesIndexRoute
}

const BalesRouteChildren: BalesRouteChildren = {
  BalesIdRoute: BalesIdRoute,
  BalesNewRoute: BalesNewRoute,
  BalesIndexRoute: BalesIndexRoute,
}

const BalesRouteWithChildren = BalesRoute._addFileChildren(BalesRouteChildren)

interface ClothesRouteChildren {
  ClothesIdRoute: typeof ClothesIdRoute
  ClothesNewRoute: typeof ClothesNewRoute
  ClothesIndexRoute: typeof ClothesIndexRoute
}

const ClothesRouteChildren: ClothesRouteChildren = {
  ClothesIdRoute: ClothesIdRoute,
  ClothesNewRoute: ClothesNewRoute,
  ClothesIndexRoute: ClothesIndexRoute,
}

const ClothesRouteWithChildren =
  ClothesRoute._addFileChildren(ClothesRouteChildren)

interface CustomersRouteChildren {
  CustomersIdRoute: typeof CustomersIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersIdRoute: CustomersIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface SalesRouteChildren {
  SalesNewRoute: typeof SalesNewRoute
}

const SalesRouteChildren: SalesRouteChildren = {
  SalesNewRoute: SalesNewRoute,
}

const SalesRouteWithChildren = SalesRoute._addFileChildren(SalesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BalesRoute: BalesRouteWithChildren,
  ClothesRoute: ClothesRouteWithChildren,
  CustomersRoute: CustomersRouteWithChildren,
  ExpensesRoute: ExpensesRoute,
  LoginRoute: LoginRoute,
  MoreRoute: MoreRoute,
  ReportsRoute: ReportsRoute,
  SalesRoute: SalesRouteWithChildren,
  PhotosIdRoute: PhotosIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
